# Generated by Django 3.2.13 on 2022-06-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('judge', models.CharField(choices=[(2, 'Python 3.8.10'), (3, 'GNU GCC C11 11.2.0'), (4, 'GNU G++14 11.2.0'), (5, 'GNU G++17 11.2.0'), (6, 'GNU G++20 11.2.0')], max_length=30)),
                ('verdict', models.CharField(choices=[('AC', 'accepted'), ('WA', 'wrong answer'), ('TE', 'time limit exceeded'), ('CE', 'compile error'), ('RE', 'runtime error'), ('TT', 'testing')], default='TT', max_length=2)),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
