# Generated by Django 4.0.3 on 2022-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcases',
            old_name='problem',
            new_name='problem_tc_fk',
        ),
        migrations.AlterField(
            model_name='solutions',
            name='submission_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('COMPILATION_ERROR', 'COMPILATION ERROR'), ('WRONG_OUTPUT', 'WRONG OUTPUT'), ('TIME_LIMIT_EXCEEDED', 'TIME LIMIT EXCEEDED'), ('RUNTIME_ERROR', 'RUNTIME ERROR')], max_length=50),
        ),
    ]
