# Generated by Django 4.0.3 on 2022-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_rename_problem_testcases_problem_tc_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'User Register/Sign In',
            },
        ),
    ]
