# Generated by Django 4.0.4 on 2022-05-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_useradmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem'},
        ),
    ]
