# Generated by Django 4.0.4 on 2022-05-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_rename_problems_problem_rename_solutions_solution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Problems',
        ),
        migrations.RenameModel(
            old_name='Solution',
            new_name='Solutions',
        ),
        migrations.RenameModel(
            old_name='TestCase',
            new_name='TestCases',
        ),
        migrations.AlterModelOptions(
            name='solutions',
            options={'verbose_name': 'Solution'},
        ),
    ]
