# Generated by Django 4.0.3 on 2022-05-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_rename_problem_problems_rename_solution_solutions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradmission',
            options={'verbose_name': 'User Admission'},
        ),
    ]
