# Generated by Django 3.2.13 on 2022-06-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('statement', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(0, 'EASY'), (1, 'MEDIUM'), (2, 'HARD')], default=0)),
                ('input', models.TextField(default='', help_text='Input format')),
                ('output', models.TextField(default='', help_text='Expected output format')),
                ('time_limit', models.IntegerField(default=1000, help_text='in milliseconds')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sample', models.BooleanField(default=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
    ]
